version: 1

env:
  - GO111MODULE=on
  - CGO_ENABLED=1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: infoscope
    main: ./cmd/infoscope
    binary: infoscope
    flags:
      - -trimpath
    ldflags:
      - -s -w 
      - -X main.Version={{.Version}}
      - -extldflags=-static
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post: upx "{{ .Path }}"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    certificate: '${artifact}.pem'
    signature: '${artifact}.sig'

snapshot:
  name_template: "{{ incpatch .Version }}-next"