name: Docker Build

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      version:
        required: true

env:
  REGISTRY: ghcr.io
  VERSION: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Convert repository name to lowercase
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO }}
          tags: |
            type=ref,event=tag
            type=raw,value=${{ env.VERSION }}
            # Add latest tag only for non-prerelease versions
            type=raw,value=latest,enable=${{ !contains(env.VERSION, '-') }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}